src/Shark.Fido2.Core/Abstractions/Helpers/ICertificateAttestationStatementProvider.cs, src/Shark.Fido2.Core/Abstractions/Validators/ICertificateAttestationStatementValidator.cs, src/Shark.Fido2.Core/Abstractions/Validators/ICryptographyValidator.cs, src/Shark.Fido2.Core/Abstractions/Validators/ISignatureAttestationStatementValidator.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Helpers/AuthenticatorDataProvider.cs, src/Shark.Fido2.Core/Helpers/CertificateAttestationStatementProvider.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AttestationStatementValidator.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/PackedAttestationStatementStategy.cs, src/Shark.Fido2.Core/Validators/CertificateAttestationStatementValidator.cs, src/Shark.Fido2.Core/Validators/Ec2CryptographyValidator.cs, src/Shark.Fido2.Core/Validators/RsaCryptographyValidator.cs, src/Shark.Fido2.Core/Validators/SignatureAttestationStatementValidator.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/PackedAttestationStatementStategyTests.cs
=> Fix issue with EC2 validation

src/Shark.Sample.Fido2/Shark.Sample.Fido2.csproj, tests/Shark.Fido2.Core.Tests/Shark.Fido2.Core.Tests.csproj, tests/Shark.Fido2.Domain.Tests/Shark.Fido2.Domain.Tests.csproj, tests/Shark.Fido2.Models.Tests/Shark.Fido2.Models.Tests.csproj
Update versions of Nuget packages
=> Update versions of Nuget packages

src/Shark.Fido2.Core/Abstractions/Services/IAppleAnonymousExtensionParserService.cs, src/Shark.Fido2.Core/Abstractions/Validators/AttestationStatementValidators/ICertificateAttestationStatementValidator.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Services/AndroidKeyAttestationExtensionParserService.cs, src/Shark.Fido2.Core/Services/AppleAnonymousExtensionParserService.cs, src/Shark.Fido2.Core/Services/CertificateAttestationStatementService.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AppleAnonymousAttestationStatementStrategy.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AttestationStatementValidator.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/CertificateAttestationStatementValidator.cs, tests/Shark.Fido2.Core.Tests/Data/AppleAnonymousAttestationWithEs256Algorithm.json, tests/Shark.Fido2.Core.Tests/Shark.Fido2.Core.Tests.csproj, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidKeyAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidSafetyNetAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AppleAnonymousAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/FidoU2fAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/PackedAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/TpmAttestationStatementStrategyTests.cs
Add Apple Anonymous Attestation Statement Format
=> Add Apple Anonymous Attestation Statement Format

src/Shark.Fido2.Core/Abstractions/Validators/AttestationStatementValidators/IAttestationStatementValidator.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AttestationStatementValidator.cs, tests/Shark.Fido2.Core.Tests/Helpers/ChallengeGeneratorTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/HashProviderTests.cs, tests/Shark.Fido2.Core.Tests/Services/AuthenticatorDataParserServiceTests.cs
=> Add unit tests

src/Shark.Fido2.Core/Constants/AttestationStatementFormatIdentifier.cs
Add XML comments for WebAuthn attestation statement format identifiers
=> Add XML comments for WebAuthn attestation statement format identifiers

src/Shark.Fido2.Core/Handlers/ClientDataHandler.cs, src/Shark.Fido2.Core/Validators/AttestationObjectValidator.cs, src/Shark.Fido2.Core/Validators/ClientDataValidator.cs, tests/Shark.Fido2.Core.Tests/ClientDataBuilder.cs, tests/Shark.Fido2.Core.Tests/Handlers/ClientDataHandlerTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationObjectValidatorTests.cs, tests/Shark.Fido2.Core.Tests/Validators/ClientDataValidatorTests.cs
Improve attestation and client data validation
=> Improve attestation and client data validation

src/Shark.Fido2.Core/Abstractions/Validators/IAttestationObjectValidator.cs, src/Shark.Fido2.Core/Abstractions/Validators/IAttestationTrustworthinessValidator.cs, src/Shark.Fido2.Core/Abstractions/Validators/IClientDataValidator.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Configurations/Fido2Configuration.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Handlers/AttestationObjectHandler.cs, src/Shark.Fido2.Core/Results/AttestationStatementInternalResult.cs, src/Shark.Fido2.Core/Validators/AttestationObjectValidator.cs, src/Shark.Fido2.Core/Validators/AttestationTrustworthinessValidator.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationObjectValidatorTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationTrustworthinessValidatorTests.cs
Add attestation trustworthiness validator
=> Add attestation trustworthiness validator

src/Shark.Fido2.Core/Helpers/BytesArrayHelper.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/TpmAttestationStatementStrategy.cs, src/Shark.Fido2.Domain/Mappers/Ec2KeyTypeMapper.cs, src/Shark.Fido2.Domain/Mappers/RsaKeyTypeMapper.cs, tests/Shark.Fido2.Core.Tests/Helpers/BytesArrayHelperTests.cs
Add ECC parameters validation for TPM attestation statement strategy
=> Add ECC parameters validation for TPM attestation statement strategy

.github/workflows/build.yml, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Add unit tests for attestation
=> Add unit tests for attestation

src/Shark.Fido2.Core/Abstractions/IAssertion.cs, src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Domain/Credential.cs, src/Shark.Fido2.Domain/PublicKeyCredentialCreationOptions.cs, src/Shark.Fido2.Domain/PublicKeyCredentialRequestOptions.cs, src/Shark.Fido2.Repositories.InMemory/CredentialRepository.cs, src/Shark.Sample.Fido2/Controllers/AssertionController.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Improve logic of creation of assertion options
=> Improve logic of creation of assertion options

src/Shark.Fido2.Repositories.InMemory/CredentialRepository.cs
Improve credentials repository
=> Improve credentials repository

src/Shark.Fido2.Core/Abstractions/Handlers/IClientDataHandler.cs, src/Shark.Fido2.Core/Abstractions/Validators/IClientDataValidator.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Handlers/ClientDataHandler.cs, src/Shark.Fido2.Core/Validators/ClientDataValidator.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs, tests/Shark.Fido2.Core.Tests/Handlers/ClientDataHandlerTests.cs, tests/Shark.Fido2.Core.Tests/Validators/ClientDataValidatorTests.cs
Add client data parsing and validation for assertion
=> Add client data parsing and validation for assertion

src/Shark.Fido2.Core/Abstractions/Handlers/IAssertionObjectHandler.cs, src/Shark.Fido2.Core/Abstractions/Validators/AttestationStatementValidators/ISignatureAttestationStatementValidator.cs, src/Shark.Fido2.Core/Abstractions/Validators/IAssertionObjectValidator.cs, src/Shark.Fido2.Core/Abstractions/Validators/ICryptographyValidator.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Handlers/AssertionObjectHandler.cs, src/Shark.Fido2.Core/Services/AuthenticatorDataParserService.cs, src/Shark.Fido2.Core/Validators/AssertionResponseValidator.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/SignatureAttestationStatementValidator.cs, src/Shark.Fido2.Domain/AuthenticatorAssertionResponse.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialAssertionMapper.cs, src/Shark.Fido2.Models/Responses/ServerAuthenticatorAssertionResponse.cs, src/Shark.Sample.Fido2/Controllers/AssertionController.cs, src/Shark.Sample.Fido2/Pages/Index.cshtml, src/Shark.Sample.Fido2/wwwroot/js/fido2-assertion.js, tests/Shark.Fido2.Models.Tests/Mappers/PublicKeyCredentialAssertionMapperTests.cs
Add parsing of assertion response
=> Add parsing of assertion response

src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Repositories.InMemory/CredentialRepository.cs
Add update of signature counter during the assertion
=> Add update of signature counter during the assertion

src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Domain/Credential.cs, src/Shark.Fido2.Domain/PublicKeyCredentialRequestOptions.cs, src/Shark.Fido2.Domain/PublicKeyCredentialRequestOptionsRequest.cs, src/Shark.Fido2.Models/Requests/ServerPublicKeyCredentialGetOptionsRequest.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Add verification that an user is an owner of a public key credential during the assertion
=> Add verification that an user is an owner of a public key credential

src/Shark.Fido2.Core/Abstractions/Validators/IUserHandlerValidator.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Validators/UserHandlerValidator.cs, tests/Shark.Fido2.Core.Tests/Validators/UserHandlerValidatorTests.cs
Extract logic for user handle validation to the separate class
=> Extract logic for user handle validation to the separate class

tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
=> Add unit tests for Assertion

.github/workflows/build_deploy.yml
Add deployment write permissions
=> Add deployment write permissions

.github/workflows/build_deploy.yml
Fix application name in deployment script
=> Fix application name in deployment script

src/Shark.Sample.Fido2/Pages/Index.cshtml
Improve main page of the website
=> Improve main page of the website

src/Shark.Sample.Fido2/Program.cs
Fix name of the XML comments file
=> Fix name of the XML comments file

src/Shark.Sample.Fido2/appsettings.Production.json
Add production configuration for web-site
=> Add production configuration for web-site

src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Constants/ExtensionIdentifiers.cs, src/Shark.Fido2.Domain/AuthenticationExtensionsClientInputs.cs, src/Shark.Fido2.Domain/AuthenticationExtensionsClientOutputs.cs, src/Shark.Fido2.Domain/PublicKeyCredentialAssertion.cs, src/Shark.Fido2.Domain/PublicKeyCredentialAttestation.cs, src/Shark.Fido2.Domain/PublicKeyCredentialCreationOptions.cs, src/Shark.Fido2.Domain/PublicKeyCredentialRequestOptions.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialAssertionMapper.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialAttestationMapper.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialCreationOptionsMapper.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialRequestOptionsMapper.cs, src/Shark.Fido2.Models/Responses/ServerAuthenticationExtensionsClientInputs.cs, src/Shark.Fido2.Models/Responses/ServerAuthenticationExtensionsClientOutputs.cs, src/Shark.Fido2.Models/Responses/ServerPublicKeyCredentialAttestation.cs, src/Shark.Fido2.Models/Responses/ServerPublicKeyCredentialCreationOptionsResponse.cs, src/Shark.Fido2.Models/Responses/ServerPublicKeyCredentialGetOptionsResponse.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs, tests/Shark.Fido2.Core.Tests/DataReaders/AttestationDataReader.cs, tests/Shark.Fido2.Core.Tests/Validators/UserHandlerValidatorTests.cs
Add properties to support input and output extensions
=> Add properties to support input and output extensions

src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Domain/AuthenticationExtensionsClientInputs.cs, src/Shark.Fido2.Domain/AuthenticationExtensionsClientOutputs.cs, src/Shark.Fido2.Domain/CredentialPropertiesOutput.cs, src/Shark.Fido2.Domain/Enums/AuthenticatorTransport.cs, src/Shark.Fido2.Domain/Enums/ResidentKeyRequirement.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialAttestationMapper.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialCreationOptionsMapper.cs, src/Shark.Fido2.Models/Responses/ServerAuthenticationExtensionsClientInputs.cs, src/Shark.Fido2.Models/Responses/ServerAuthenticationExtensionsClientOutputs.cs, src/Shark.Fido2.Models/Responses/ServerCredentialPropertiesOutput.cs, src/Shark.Sample.Fido2/wwwroot/js/fido2-attestation.js
Add support for credential properties extension
=> Add support for credential properties extension

src/Shark.Fido2.Core/Validators/AttestationStatementValidators/NoneAttestationStatementStrategy.cs
Fix issue with None attestation statement
=> Fix issue with None attestation statement

src/Shark.Fido2.Core/Validators/AttestationStatementValidators/PackedAttestationStatementStrategy.cs, src/Shark.Fido2.Core/Validators/UserHandlerValidator.cs
Fix issue with alg validation for Packed attestation statement
=> Fix issue with alg validation for Packed attestation statement

src/Shark.Fido2.Core/Validators/AttestationStatementValidators/FidoU2fAttestationStatementStrategy.cs, tests/Shark.Fido2.Core.Tests/DataReaders/ClientDataBuilder.cs
Add AAGUID validation for FIDO U2F attestation
=> Add AAGUID validation for FIDO U2F attestation

src/Shark.Fido2.Core/Dictionaries/TpmCapabilitiesVendors.cs
=> Add TPM test vendor

src/Shark.Fido2.Core/Services/AuthenticatorDataParserService.cs, tests/Shark.Fido2.Core.Tests/Services/AuthenticatorDataParserServiceTests.cs
Fix issue with authenticator data parser
=> Fix issue with authenticator data parser

src/Shark.Fido2.Core/Abstractions/IAttestation.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialCreationOptionsMapper.cs, src/Shark.Fido2.Repositories.InMemory/CredentialRepository.cs, src/Shark.Sample.Fido2/Controllers/AttestationController.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Add excluding credentials for attestation
=> Add excluding credentials for attestation

src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Constants/AttestationStatementFormatIdentifier.cs, src/Shark.Fido2.Core/Constants/PublicKeyAlgorithms.cs, src/Shark.Fido2.Domain/Enums/PublicKeyAlgorithm.cs, src/Shark.Fido2.Domain/Mappers/Ec2KeyTypeMapper.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Refine all supported algorithms
=> Refine all supported algorithms

src/Shark.Fido2.Core/Validators/AssertionResponseValidator.cs, src/Shark.Fido2.Core/Validators/AttestationObjectValidator.cs
Fix issue with User Present bit of the flags in authData
=> Fix issue with User Present bit of the flags in authData

src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Validators/ClientDataValidator.cs, src/Shark.Fido2.Models/Responses/ServerPublicKeyCredentialCreationOptionsResponse.cs
=> Fix small styling issues

.github/workflows/build_push_nuget_sdk.yml, src/Shark.Fido2.Core/Comparers/BytesArrayComparer.cs, src/Shark.Fido2.Core/README.md, src/Shark.Fido2.Core/Shark.Fido2.Core.csproj
=> Add nuget package support

src/Shark.Fido2.Common/Shark.Fido2.Common.csproj, src/Shark.Fido2.Core/Shark.Fido2.Core.csproj, src/Shark.Fido2.Metadata.Core/Shark.Fido2.Metadata.Core.csproj, src/Shark.Sample.Fido2/Shark.Sample.Fido2.csproj, tests/Shark.Fido2.Core.Tests/Shark.Fido2.Core.Tests.csproj, tests/Shark.Fido2.Domain.Tests/Shark.Fido2.Domain.Tests.csproj, tests/Shark.Fido2.Models.Tests/Shark.Fido2.Models.Tests.csproj
=> Update projects dependencies

src/Shark.Fido2.Core/Configurations/Fido2Configuration.cs, src/Shark.Fido2.Core/Services/AuthenticatorDataParserService.cs, src/Shark.Fido2.Core/Validators/AttestationObjectValidator.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AttestationCertificateValidator.cs, src/Shark.Fido2.Metadata.Core/Abstractions/ICertificateValidator.cs, src/Shark.Fido2.Metadata.Core/Abstractions/IMetadataBlobService.cs, src/Shark.Fido2.Metadata.Core/Abstractions/IMetadataCachedService.cs, src/Shark.Fido2.Metadata.Core/Abstractions/IMetadataReaderService.cs, src/Shark.Fido2.Metadata.Core/Abstractions/Repositories/IHttpClientConformanceTestRepository.cs, src/Shark.Fido2.Metadata.Core/CertificateValidator.cs, src/Shark.Fido2.Metadata.Core/DependencyInjection.cs, src/Shark.Fido2.Metadata.Core/Mappers/MetadataBlobPayloadItemMapper.cs, src/Shark.Fido2.Metadata.Core/MetadataBlobService.cs, src/Shark.Fido2.Metadata.Core/MetadataCachedService.cs, src/Shark.Fido2.Metadata.Core/MetadataConformanceTestService.cs, src/Shark.Fido2.Metadata.Core/MetadataReaderService.cs, src/Shark.Fido2.Metadata.Core/MetadataService.cs, src/Shark.Fido2.Metadata.Core/Models/MetadataBlobPayload.cs, src/Shark.Fido2.Metadata.Core/Repositories/HttpClientConformanceTestRepository.cs, src/Shark.Fido2.Metadata.Core/Shark.Fido2.Metadata.Core.csproj, src/Shark.Fido2.Metadata.Domain/Constants/AuthenticatorStatus.cs, src/Shark.Fido2.Metadata.Domain/MetadataBlobPayloadItem.cs, src/Shark.Fido2.Metadata.Domain/StatusReport.cs, src/Shark.Sample.Fido2/Properties/launchSettings.json, src/Shark.Sample.Fido2/Shark.Sample.Fido2.csproj, src/Shark.Sample.Fido2/appsettings.Development.json, src/Shark.Sample.Fido2/appsettings.Production.json, src/Shark.Sample.Fido2/appsettings.Test.json
=> Improve metadata service

src/Shark.Fido2.Core/Abstractions/Validators/AttestationStatementValidators/IAndroidSafetyNetJwsResponseValidator.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AndroidSafetyNetAttestationStatementStrategy.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AndroidSafetyNetJwsResponseValidator.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AttestationCertificateValidator.cs, src/Shark.Fido2.Core/Validators/AttestationTrustworthinessValidator.cs, src/Shark.Fido2.Metadata.Core/CertificateValidator.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidKeyAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidSafetyNetAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AppleAnonymousAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/FidoU2fAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/PackedAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/TpmAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationTrustworthinessValidatorTests.cs
Enable Android Safety Net validation
=> Enable Android Safety Net validation

src/Shark.Sample.Fido2/wwwroot/js/fido2-assertion.js, src/Shark.Sample.Fido2/wwwroot/js/fido2-attestation.js, src/Shark.Sample.Fido2/wwwroot/js/site.js
=> Improve UI error handling

src/Shark.Fido2.Common/Extensions/ConvertExtensions.cs, src/Shark.Sample.Fido2/Pages/Index.cshtml, src/Shark.Sample.Fido2/Pages/Index.cshtml.cs, src/Shark.Sample.Fido2/Pages/Shared/_Layout.cshtml, src/Shark.Sample.Fido2/wwwroot/js/fido2-assertion.js, src/Shark.Sample.Fido2/wwwroot/js/fido2-attestation.js, src/Shark.Sample.Fido2/wwwroot/js/site.js
Update UI / UX of the demo portal
=> Update UI / UX of the demo portal

src/Shark.Sample.Fido2/Pages/Index.cshtml, src/Shark.Sample.Fido2/wwwroot/css/site.css, src/Shark.Sample.Fido2/wwwroot/js/site.js
=> Improve UI of the main page

src/Shark.Sample.Fido2/Pages/Index.cshtml, src/Shark.Sample.Fido2/Pages/Shared/_Layout.cshtml, src/Shark.Sample.Fido2/wwwroot/css/site.css
Improve width handling on the main page
=> Improve width handling on the main page

src/Shark.Sample.Fido2/Pages/Shared/_Layout.cshtml, src/Shark.Sample.Fido2/wwwroot/css/site.css
- Improve spacing on the main page
- Change header of the pages
=> Improve spacing on the main page

src/Shark.Sample.Fido2/Controllers/AssertionController.cs, src/Shark.Sample.Fido2/Controllers/AttestationController.cs, src/Shark.Sample.Fido2/Program.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/TpmAttestationStatementStrategyTests.cs
Improve logging for sample project
=> Improve logging

src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Constants/AttestationStatementFormatIdentifier.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AndroidSafetyNetAttestationStatementStrategy.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/NoneAttestationStatementStrategy.cs, src/Shark.Fido2.Domain/Constants/AttestationConveyancePreference.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Improve attestation and assertion implementation & unit tests
=> Improve attestation and assertion implementation & unit tests

.github/workflows/build_push_nuget_sdk.yml, src/Shark.Fido2.Models/README.md, src/Shark.Fido2.Models/Shark.Fido2.Models.csproj, tests/Shark.Fido2.Models.Tests/Shark.Fido2.Models.Tests.csproj
Add Nuget for Shark.Fido2.Models project
=> Add Nuget for Shark.Fido2.Models project

.github/workflows/build_deploy.yml, .github/workflows/build_docker_image.yml, src/Shark.Fido2.Core/Shark.Fido2.Core.csproj, src/Shark.Fido2.Domain/Shark.Fido2.Domain.csproj, src/Shark.Fido2.Metadata.Core/Shark.Fido2.Metadata.Core.csproj, src/Shark.Fido2.Models/Shark.Fido2.Models.csproj
Remove unused projects references
=> Remove unused projects references

.editorconfig, src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Refactor in-memory CredentialRepository
=> Refactor in-memory CredentialRepository

.github/workflows/build.yml, .github/workflows/build_docker_image.yml, .github/workflows/build_nuget_packages.yml, .github/workflows/deploy.yml, README.md
=> Add Nuget packages to readme

.github/workflows/build_nuget_packages.yml
Update version pattern for NuGet packages
=> Update version pattern for NuGet packages

src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.Core/Validators/UserHandlerValidator.cs, src/Shark.Sample.Fido2/wwwroot/js/fido2-assertion.js, src/Shark.Sample.Fido2/wwwroot/js/fido2-attestation.js
Improve assertion verification logic
=> Improve assertion verification logic

.github/workflows/deploy_portal.yml, src/Shark.Portal.Fido2/appsettings.Production.json
=> Add portal deployment

README.md, src/Shark.Portal.Fido2/Controllers/AssertionController.cs
=> Add documentation

src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Metadata.Core/DependencyInjection.cs, src/Shark.Fido2.Metadata.Core/Services/MetadataCachedService.cs
Add caching of individual entries for metadata service
=> Add caching of individual entries for metadata service

src/Shark.Portal.Fido2/appsettings.Production.json
Update production settings for portal
=> Update production settings for portal

src/Shark.Fido2.Core/Converters/CborConverter.cs, src/Shark.Fido2.Core/Services/AuthenticatorDataParserService.cs, src/Shark.Sample.Fido2/Program.cs, tests/Shark.Fido2.Core.Tests/Handlers/AttestationObjectHandlerTests.cs
Fix issue with leftovers bytes in authenticator data
=> Fix issue with leftovers bytes in authenticator data

src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
=> Update Portal dependencies

src/Shark.Portal.Fido2/Pages/Shared/_Layout.cshtml, src/Shark.Portal.Fido2/Program.cs, src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
Add minification of JS and CSS files for Portal
=> Add minification of JS and CSS files for Portal

src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs
Add trimming of input parameters
=> Add trimming of input parameters

src/Shark.Fido2.Core/Abstractions/IAssertion.cs, src/Shark.Fido2.Core/Abstractions/IAttestation.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Sample.Fido2/Controllers/AssertionController.cs, src/Shark.Sample.Fido2/Controllers/AttestationController.cs
Add support for cancellation tokens
=> Add support for cancellation tokens

src/Shark.Portal.Fido2/Controllers/AssertionController.cs, src/Shark.Portal.Fido2/Controllers/AttestationController.cs, src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
Add cancellation token support for the portal
=> Add cancellation token support for the portal

src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
=> Update version of the portal

src/Shark.Fido2.Core/Validators/UserHandlerValidator.cs, src/Shark.Fido2.Models/Requests/ServerPublicKeyCredentialCreationOptionsRequest.cs, src/Shark.Portal.Fido2/wwwroot/js/site.js, src/Shark.Sample.Fido2/Pages/Index.cshtml, src/Shark.Sample.Fido2/wwwroot/js/fido2-assertion.js, src/Shark.Sample.Fido2/wwwroot/js/fido2-attestation.js, src/Shark.Sample.Fido2/wwwroot/js/site.js
Improve logic for usernameless login
=> Improve logic for usernameless login

src/Shark.Portal.Fido2/Program.cs, src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
Enhance security headers and update FIDO2 package versions
=> Enhance security headers and update FIDO2 package versions

src/Shark.Fido2.InMemory/CredentialRepository.cs
Add expiration of memory credential repository
=> Add expiration of memory credential repository

src/Shark.Portal.Fido2/Pages/Index.cshtml, src/Shark.Portal.Fido2/Pages/Shared/_Layout.cshtml, src/Shark.Portal.Fido2/Program.cs, src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj, src/Shark.Portal.Fido2/wwwroot/css/site.css
Add disclaimer about memory cache for the portal
=> Add disclaimer about memory cache for the portal

src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
Fix styling issues in the portal
=> Fix styling issues in the portal

src/Shark.Portal.Fido2/Pages/Shared/_Layout.cshtml, src/Shark.Portal.Fido2/Pages/_ViewImports.cshtml
Fix issue with caching of CSS and JS files
=> Fix issue with caching of CSS and JS files

src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Improve performance of attestation
=> Improve performance of attestation

.github/workflows/build_nuget_packages.yml, README.md
=> Increase NuGet versions

src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
Update portal NuGet dependencies
=> Update portal NuGet dependencies

src/Shark.Fido2.Core/Entities/CredentialEntity.cs, src/Shark.Fido2.Core/Entities/CredentialPublicKeyEntity.cs, src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs
=> Add entities for datastores

src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, src/Shark.Fido2.Domain/CredentialDescriptor.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Add a lightweight descriptor of a credential
=> Add a lightweight descriptor of a credential

.github/workflows/build_nuget_sqlserver_packages.yml, README.md, src/Shark.Fido2.Core/Entities/CredentialEntity.cs, src/Shark.Fido2.Core/Entities/CredentialPublicKeyEntity.cs, src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, src/Shark.Fido2.InMemory/DependencyInjection.cs, src/Shark.Fido2.SqlServer/CredentialRepository.cs, src/Shark.Fido2.SqlServer/DatabaseSettings.cs, src/Shark.Fido2.SqlServer/DependencyInjection.cs, src/Shark.Fido2.SqlServer/README.md, src/Shark.Fido2.SqlServer/Shark.Fido2.SqlServer.csproj, src/Shark.Fido2.SqlServer/SqlConnectionFactory.cs, src/Shark.Fido2.sln, src/Shark.Sample.Fido2/Program.cs, src/Shark.Sample.Fido2/Shark.Sample.Fido2.csproj, src/Shark.Sample.Fido2/appsettings.Development.json
=> Add support for SQL Server

src/Shark.Fido2.SqlServer/Shark.Fido2.SqlServer.csproj
Fix issue with readme file in SQL Server library
=> Fix issue with readme file in SQL Server library

scripts/sqlserver/sqlserver_table_creation.sql
Add SQL Server creation script
=> Add SQL Server creation script

src/Shark.Fido2.InMemory/DependencyInjection.cs, src/Shark.Fido2.SqlServer/DependencyInjection.cs, src/Shark.Sample.Fido2/Program.cs, tests/Shark.Fido2.Core.Integration.Tests/AttestationIntegrationTests.cs
Rename dependency injection methods for data stores
=> Rename dependency injection methods for data stores

src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialCreationOptionsMapper.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialRequestOptionsMapper.cs
Fix issue with transport mapping. Update models mapper
=> Fix issue with transport mapping. Update models mapper

README.md
Add FIDO Conformance Tool results
=> Add FIDO Conformance Tool results

src/Shark.Portal.Fido2/Controllers/AssertionController.cs, src/Shark.Portal.Fido2/Controllers/AttestationController.cs, src/Shark.Portal.Fido2/Program.cs, src/Shark.Portal.Fido2/Shark.Portal.Fido2.csproj
=> Update portal Fido2 packages

scripts/sqlserver/sqlserver_table_creation.sql, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Entities/CredentialEntity.cs, src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, src/Shark.Fido2.Core/Validators/UserHandlerValidator.cs, src/Shark.Fido2.Domain/Credential.cs, src/Shark.Fido2.Domain/Options/PublicKeyCredentialCreationOptionsRequest.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, src/Shark.Fido2.Models/Mappers/PublicKeyCredentialCreationOptionsRequestMapper.cs, src/Shark.Fido2.SqlServer/CredentialRepository.cs, src/Shark.Sample.Fido2/appsettings.Development.json, tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs, tests/Shark.Fido2.Core.Tests/Validators/UserHandlerValidatorTests.cs, tests/Shark.Fido2.Models.Tests/Mappers/PublicKeyCredentialCreationOptionsRequestMapperTests.cs
Add display name to the data stores
=> Add display name to the data stores

src/Shark.Fido2.Core/Validators/ClientDataValidator.cs
Add comment for token binding support
=> Add comment for token binding support

src/Shark.Portal.Fido2/Pages/Index.cshtml, src/Shark.Portal.Fido2/wwwroot/js/site.js
Improve usability of the portal's main page
=> Improve usability of the portal's main page

src/Shark.Portal.Fido2/Pages/About.cshtml, src/Shark.Portal.Fido2/Pages/About.cshtml.cs, src/Shark.Portal.Fido2/Pages/Shared/_Layout.cshtml, src/Shark.Portal.Fido2/wwwroot/css/site.css, src/Shark.Portal.Fido2/wwwroot/js/site.js
=> Add About page for the portal

scripts/sqlserver/sqlserver_table_creation.sql, src/Shark.Fido2.Core/Entities/CredentialEntity.cs, src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, src/Shark.Fido2.Domain/Credential.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, src/Shark.Fido2.Sample/Program.cs, src/Shark.Fido2.SqlServer/CredentialRepository.cs
Add audit trail columns and properties
=> Add audit trail columns and properties

src/Shark.Fido2.Core/Entities/CredentialEntity.cs, src/Shark.Fido2.Domain/Credential.cs
Make credential's UpdatedAt property nullable
=> Make credential's UpdatedAt property nullable

src/Shark.Fido2.Portal/Pages/CredentialsDetails.cshtml, src/Shark.Fido2.Portal/Pages/CredentialsDetails.cshtml.cs, src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj
Add audit trails properties for portal
=> Add audit trails properties for portal

src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, tests/Shark.Fido2.Core.Tests/Comparers/BytesArrayComparerTests.cs, tests/Shark.Fido2.Core.Tests/Mappers/CredentialMapperTests.cs, tests/Shark.Fido2.Core.Tests/Mappers/Ec2KeyTypeMapperTests.cs, tests/Shark.Fido2.Core.Tests/Mappers/RsaKeyTypeMapperTests.cs
Improve tests coverage for core mappers
=> Improve tests coverage for core mappers

src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj
Update portal Fido2 packages to version 1.0.2
=> Update portal Fido2 packages to version 1.0.2

src/Shark.Fido2.Core/Abstractions/IUserIdGenerator.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Helpers/UserIdGenerator.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/UserIdGeneratorTests.cs
Create extension point for WebAuthn User ID
=> Create extension point for WebAuthn User ID

README.md, src/Shark.Fido2.Core/Configurations/Fido2Configuration.cs, src/Shark.Fido2.Metadata.Core/Configurations/MetadataServiceConfiguration.cs
Add documentation for configuration
=> Add documentation for configuration

src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, src/Shark.Fido2.SqlServer/CredentialRepository.cs
Update names of the parameters in repositories
=> Update names of the parameters in repositories

src/Shark.Fido2.Core/Abstractions/IAttestation.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Portal/Controllers/AttestationController.cs, src/Shark.Fido2.Sample/Controllers/AttestationController.cs, src/Shark.Fido2.Sample/Swagger/ServerPublicKeyCredentialCreationOptionsRequestExample.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs
Rename options method for attestation
=> Rename options method for attestation

src/Shark.Fido2.Portal/appsettings.Development.json, src/Shark.Fido2.Portal/appsettings.Production.json, src/Shark.Fido2.Sample/appsettings.Development.json, src/Shark.Fido2.Sample/appsettings.Production.json, src/Shark.Fido2.Sample/appsettings.Test.json
Update configurations of portals to improve documentation
=> Update configurations of portals to improve documentation

README.md
=> Add supported algorithms

src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, src/Shark.Fido2.SqlServer/CredentialRepository.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs
Simplify signature of UpdateSignCount method of repositories
=> Simplify signature of UpdateSignCount method of repositories

src/Shark.Fido2.Portal/Pages/Shared/_Layout.cshtml
Add meta description for the portal
=> Add meta description for the portal

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Update README.md with contributions section
=> Update README.md with contributions section

THIRD_PARTY_LICENSES.txt
=> Add third party licenses

src/Shark.Fido2.Portal/Pages/Index.cshtml, src/Shark.Fido2.Portal/wwwroot/css/site.css, src/Shark.Fido2.Portal/wwwroot/js/site.js
Fix issue with get credentials button on portal
=> Fix issue with get credentials button on portal

.github/workflows/build_nuget_core_packages.yml, .github/workflows/build_nuget_dynamodb_packages.yml, .github/workflows/build_nuget_inmemory_packages.yml, .github/workflows/build_nuget_models_packages.yml, .github/workflows/build_nuget_sqlserver_packages.yml, README.md, src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj
=> Release 1.0.3

CONTRIBUTING.md
Update contributing instruction
=> Update contributing instruction

src/Shark.Fido2.DynamoDB/Abstractions/IAmazonDynamoDbClientFactory.cs, src/Shark.Fido2.DynamoDB/AmazonDynamoDbClientFactory.cs, src/Shark.Fido2.DynamoDB/AmazonDynamoDbConfiguration.cs, src/Shark.Fido2.DynamoDB/AttributeNames.cs, src/Shark.Fido2.DynamoDB/CredentialEntityMapper.cs, src/Shark.Fido2.DynamoDB/CredentialRepository.cs, src/Shark.Fido2.DynamoDB/DependencyInjection.cs, src/Shark.Fido2.DynamoDB/ExpressionNames.cs, src/Shark.Fido2.DynamoDB/README.md, src/Shark.Fido2.InMemory/CredentialRepository.cs, src/Shark.Fido2.Sample/appsettings.Development.json, src/Shark.Fido2.SqlServer/CredentialRepository.cs, src/Shark.Fido2.SqlServer/README.md
=> Improve data stores

scripts/sqlserver/sqlserver_table_creation.sql, src/Shark.Fido2.Core/Abstractions/Repositories/ICredentialRepository.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Entities/CredentialEntity.cs, src/Shark.Fido2.Core/Mappers/CredentialMapper.cs, src/Shark.Fido2.Domain/Credential.cs, src/Shark.Fido2.DynamoDB/AttributeNames.cs, src/Shark.Fido2.DynamoDB/CredentialEntityMapper.cs, src/Shark.Fido2.DynamoDB/CredentialRepository.cs, src/Shark.Fido2.DynamoDB/ExpressionNames.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, src/Shark.Fido2.SqlServer/CredentialRepository.cs
Add last used at property for credential
=> Add last used at property for credential

.github/workflows/build_nuget_packages.yml
Create pipeline to run Nuget builds for multiple packages in parallel
=> Create pipeline to run Nuget builds for multiple packages in parallel

src/Shark.Fido2.Portal/Pages/CredentialsDetails.cshtml, src/Shark.Fido2.Portal/Pages/CredentialsDetails.cshtml.cs, src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj
Update portal to 1.0.4 version
=> Update portal to 1.0.4 version

scripts/sqlserver/sqlserver_table_creation.sql, src/Shark.Fido2.Core/Helpers/UserIdGenerator.cs, tests/Shark.Fido2.Core.Integration.Tests/AttestationIntegrationTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/UserIdGeneratorTests.cs
- Fix issue with standard user id generator 
- Update size of UserHandle database column for SQL Server
=> Fix issue with standard user id generator

src/Shark.Fido2.Core/Configurations/Fido2ConfigurationValidator.cs, tests/Shark.Fido2.Core.Tests/Configurations/Fido2ConfigurationValidatorTests.cs
Fix issue with configuration validation
=> Fix issue with configuration validation

.github/workflows/build_nuget_packages.yml, src/Shark.Fido2.Portal/Pages/Error.cshtml, src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj, src/Shark.Fido2.Portal/appsettings.Development.json, src/Shark.Fido2.Portal/appsettings.Production.json
=> Release 1.0.5

src/Shark.Fido2.Portal/Pages/Index.cshtml, src/Shark.Fido2.Portal/Pages/NonDiscoverableCredentials.cshtml, src/Shark.Fido2.Portal/Pages/NonDiscoverableCredentials.cshtml.cs, src/Shark.Fido2.Portal/Pages/Shared/_Layout.cshtml, src/Shark.Fido2.Portal/Program.cs, src/Shark.Fido2.Portal/wwwroot/css/landing.css, src/Shark.Fido2.Portal/wwwroot/css/site.css
=> Add landing page

src/Shark.Fido2.Core/README.md, src/Shark.Fido2.DynamoDB/README.md, src/Shark.Fido2.InMemory/README.md, src/Shark.Fido2.Models/README.md, src/Shark.Fido2.SqlServer/README.md
Remove non-standard characters from README files
=> Remove non-standard characters from README files

README.md, src/Shark.Fido2.Portal/Pages/Index.cshtml
Fix links to JS files in the readme
=> Fix links to JS files in the readme

README.md
=> Fix links in the README file

src/Shark.Fido2.Core/README.md, src/Shark.Fido2.DynamoDB/README.md, src/Shark.Fido2.InMemory/README.md, src/Shark.Fido2.Models/README.md, src/Shark.Fido2.Portal/Pages/About.cshtml, src/Shark.Fido2.Portal/Pages/Index.cshtml, src/Shark.Fido2.Portal/Pages/Shared/_Layout.cshtml, src/Shark.Fido2.Portal/wwwroot/css/landing.css, src/Shark.Fido2.Portal/wwwroot/css/site.css, src/Shark.Fido2.SqlServer/README.md
=> Legal changes

.github/ISSUE_TEMPLATE/issue-report.md
=> Add issue templates

README.md
Update specification description in README
=> Update specification description in README

src/Shark.Fido2.Portal/Program.cs, src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj
Add Application Insight for the Portal
=> Add Application Insight for the Portal

src/Shark.Fido2.Portal/Pages/Shared/_Layout.cshtml
Add Open Graph Tags for the portal
=> Add Open Graph Tags for the portal

src/Shark.Fido2.Core/Shark.Fido2.Core.csproj, src/Shark.Fido2.DynamoDB/Shark.Fido2.DynamoDB.csproj, src/Shark.Fido2.InMemory/Shark.Fido2.InMemory.csproj, src/Shark.Fido2.Models/Shark.Fido2.Models.csproj, src/Shark.Fido2.SqlServer/Shark.Fido2.SqlServer.csproj
Extend tags for Nuget packages
=> Extend tags for Nuget packages

src/Shark.Fido2.Portal/wwwroot/css/site.css
Improve inputs for the portal on Chrome and Safari
=> Improve inputs for the portal on Chrome and Safari

src/Shark.Fido2.Portal/Pages/NonDiscoverableCredentials.cshtml, src/Shark.Fido2.Portal/wwwroot/css/site.css, src/Shark.Fido2.Portal/wwwroot/js/dc/site-dc.js, src/Shark.Fido2.Portal/wwwroot/js/ndc/site-ndc.js
Disable inputs while credential operations are in progress in the portal
=> Disable inputs while credential operations are in progress in the portal

src/Shark.Fido2.Portal/Pages/DiscoverableCredentials.cshtml, src/Shark.Fido2.Portal/Pages/NonDiscoverableCredentials.cshtml
Fix issue with credentials links in the portal
=> Fix issue with credentials links in the portal

src/Shark.Fido2.Portal/Pages/DiscoverableCredentials.cshtml, src/Shark.Fido2.Portal/Pages/NonDiscoverableCredentials.cshtml, src/Shark.Fido2.Portal/wwwroot/js/dc/site-dc.js, src/Shark.Fido2.Portal/wwwroot/js/ndc/site-ndc.js, src/Shark.Fido2.Portal/wwwroot/js/shared/utilities.js
Add verification whether browser is supported in the portal
=> Add verification whether browser is supported in the portal

src/Shark.Fido2.Portal/wwwroot/js/dc/site-dc.js, src/Shark.Fido2.Portal/wwwroot/js/ndc/site-ndc.js, src/Shark.Fido2.Portal/wwwroot/js/shared/utilities.js
Fix issue checking WebAuthn support in the portal
=> Fix issue checking WebAuthn support in the portal

src/Shark.Fido2.Portal/wwwroot/js/dc/fido2-dc-attestation.js, src/Shark.Fido2.Portal/wwwroot/js/ndc/fido2-ndc-attestation.js
Handle invalid state error in the portal
=> Handle invalid state error in the portal

src/Shark.Fido2.Portal/Pages/About.cshtml, src/Shark.Fido2.Portal/Pages/DiscoverableCredentials.cshtml, src/Shark.Fido2.Portal/Pages/NonDiscoverableCredentials.cshtml, src/Shark.Fido2.Portal/Pages/Resources.cshtml, src/Shark.Fido2.Portal/Program.cs
=> Split sections in the portal

README.md, src/Shark.Fido2.Portal/Pages/Shared/_Layout.cshtml, src/Shark.Fido2.Portal/wwwroot/css/landing.css
- Remove Resources and About pages from the portal
- Change border size on the landing page on the portal
- Update README
=> Remove Resources and About pages from the portal

src/Shark.Fido2.Portal/Pages/Index.cshtml, src/Shark.Fido2.Portal/wwwroot/css/landing.css, src/Shark.Fido2.Portal/wwwroot/css/site.css
Improve landing page of the portal
=> Improve landing page of the portal

src/Shark.Fido2.Core/Constants/CoseAlgorithms.cs
Update list of the required Cose algorithms
=> Update list of the required Cose algorithms

src/Shark.Fido2.Portal/Pages/Index.cshtml, src/Shark.Fido2.Portal/wwwroot/css/landing.css, src/Shark.Fido2.Portal/wwwroot/css/site.css
=> Minor portal improvements

src/Shark.Fido2.Portal/Pages/Documentation.cshtml, src/Shark.Fido2.Portal/Pages/Index.cshtml, src/Shark.Fido2.Portal/wwwroot/css/site.css, src/Shark.Fido2.Portal/wwwroot/sitemap.xml, src/Shark.Fido2.Sample/Program.cs, src/Shark.Fido2.Sample/appsettings.Development.json
=> Add datastore to the docs

src/Shark.Fido2.Portal/Pages/Shared/_Layout.cshtml, src/Shark.Fido2.Portal/wwwroot/css/site.css, src/Shark.Fido2.Portal/wwwroot/js/shared/highlight.js, src/Shark.Fido2.Portal/wwwroot/lib/highlight.js/highlight.min.css, src/Shark.Fido2.Portal/wwwroot/lib/highlight.js/highlight.min.js, src/Shark.Fido2.Portal/wwwroot/lib/highlight.js/languages/csharp.min.js, src/Shark.Fido2.Portal/wwwroot/lib/highlight.js/languages/javascript.min.js, src/Shark.Fido2.Portal/wwwroot/lib/highlight.js/languages/json.min.js
Add code highlights for documentation
=> Add code highlights for documentation

README.md, src/Shark.Fido2.Portal/Pages/Documentation.cshtml, src/Shark.Fido2.Portal/wwwroot/css/landing.css, src/Shark.Fido2.Portal/wwwroot/css/site.css, src/Shark.Fido2.Portal/wwwroot/sitemap.xml
- Add overview for the docs page
- Add table of the contents
- Move Configuration upper
- Update README
=> Add overview for the docs page

src/Shark.Fido2.Sample/Controllers/AssertionController.cs, src/Shark.Fido2.Sample/Controllers/AttestationController.cs, src/Shark.Fido2.Sample/Pages/Index.cshtml, src/Shark.Fido2.Sample/Pages/Shared/_Layout.cshtml, src/Shark.Fido2.Sample/Program.cs, src/Shark.Fido2.Sample/wwwroot/css/site.css, src/Shark.Fido2.Sample/wwwroot/js/fido2-assertion.js, src/Shark.Fido2.Sample/wwwroot/js/fido2-attestation.js, src/Shark.Fido2.Sample/wwwroot/js/site.js, src/Shark.Fido2.Sample/wwwroot/robots.txt, src/Shark.Fido2.Sample/wwwroot/sitemap.xml
- Improve layout
- Improve logging on client and server sides
- Fix issue with using data store
=> Improve sample application

README.md, src/Shark.Fido2.Sample/wwwroot/css/site.css, src/Shark.Fido2.Sample/wwwroot/js/fido2-assertion.js, src/Shark.Fido2.Sample/wwwroot/js/fido2-attestation.js
- Minor UI improvement for sample application
- Update README
=> Minor UI improvement for sample application

src/Shark.Fido2.Sample/Controllers/AssertionController.cs, src/Shark.Fido2.Sample/Controllers/AttestationController.cs, src/Shark.Fido2.Sample/Filters/RestApiExceptionFilter.cs, src/Shark.Fido2.Sample/Pages/Error.cshtml
Improve error handling for sample application
=> Improve error handling for sample application

src/Shark.Fido2.Sample/Pages/Index.cshtml
Fix layout on sample application
=> Fix layout on sample application

.editorconfig, .github/workflows/sonarcloud.yml, sonar-project.properties, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Converters/CborConverter.cs, src/Shark.Fido2.Core/Helpers/BytesArrayHelper.cs, src/Shark.Fido2.Core/Validators/AttestationTrustworthinessValidator.cs, src/Shark.Fido2.DynamoDB/CredentialEntityMapper.cs, src/Shark.Fido2.Metadata.Core/Repositories/HttpClientRepository.cs, src/Shark.Fido2.Metadata.Core/Services/MetadataCachedTestService.cs, src/Shark.Fido2.Portal/Pages/Error.cshtml.cs, src/Shark.Fido2.Portal/Shark.Fido2.Portal.csproj, src/Shark.Fido2.Sample/Pages/Error.cshtml.cs, src/Shark.Fido2.Sample/Shark.Fido2.Sample.csproj, tests/Shark.Fido2.Core.Integration.Tests/DataReaders/DataReader.cs, tests/Shark.Fido2.Core.Tests/Mappers/CredentialMapperTests.cs, tests/Shark.Fido2.Core.Tests/Services/AndroidKeyAttestationExtensionParserServiceTests.cs
- Further improve code base
- Update SonarQube build definition
=> Further improve code base

README.md
Update documentation in the README
=> Update documentation in the README

src/Shark.Fido2.Core/Validators/ClientDataValidator.cs, tests/Shark.Fido2.Core.Tests/Validators/ClientDataValidatorTests.cs
Refactor client data validator
=> Refactor client data validator

tests/Shark.Fido2.Core.Tests/Comparers/BytesArrayComparerTests.cs, tests/Shark.Fido2.Core.Tests/Configurations/Fido2ConfigurationValidatorTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/BytesArrayHelperTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/ChallengeGeneratorTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/HashProviderTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/UserIdGeneratorTests.cs, tests/Shark.Fido2.Core.Tests/Mappers/CredentialMapperTests.cs, tests/Shark.Fido2.Core.Tests/Mappers/Ec2KeyTypeMapperTests.cs, tests/Shark.Fido2.Core.Tests/Mappers/RsaKeyTypeMapperTests.cs, tests/Shark.Fido2.Core.Tests/Mappers/TmpHashAlgorithmMapperTests.cs, tests/Shark.Fido2.Core.Tests/Services/AndroidKeyAttestationExtensionParserServiceTests.cs, tests/Shark.Fido2.Core.Tests/Services/AndroidSafetyNetJwsResponseParserServiceTests.cs, tests/Shark.Fido2.Core.Tests/Services/SubjectAlternativeNameParserServiceTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidKeyAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidSafetyNetAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AppleAnonymousAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/FidoU2fAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/NoneAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/PackedAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/TpmAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Domain.Tests/AssertionCompleteResultTests.cs, tests/Shark.Fido2.Domain.Tests/AttestationCompleteResultTests.cs, tests/Shark.Fido2.Metadata.Core.Tests/Mappers/MetadataPayloadItemMapperTests.cs
- Add unit tests for AndroidSafetyNetJwsResponseParserService
- Update existing unit tests
=> Add unit tests for AndroidSafetyNetJwsResponseParserService

tests/Shark.Fido2.Models.Tests/Mappers/PublicKeyCredentialCreationOptionsMapperTests.cs, tests/Shark.Fido2.Models.Tests/Mappers/PublicKeyCredentialRequestOptionsMapperTests.cs
Add unit tests for model's mappers
=> Add unit tests for model's mappers

.github/workflows/sonarcloud.yml
Update SonarQube build definition and remove reference to the portal
=> Update SonarQube build definition and remove reference to the portal

.github/workflows/build_docker_image.yml
Update docker build to push to Docker Hub
=> Update docker build

src/Shark.Fido2.Core/Abstractions/Validators/IAssertionParametersValidator.cs, src/Shark.Fido2.Core/Abstractions/Validators/IAttestationParametersValidator.cs, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Attestation.cs, src/Shark.Fido2.Core/Constants/CoseAlgorithmsSet.cs, src/Shark.Fido2.Core/DependencyInjection.cs, src/Shark.Fido2.Core/Validators/AssertionParametersValidator.cs, src/Shark.Fido2.Core/Validators/AttestationParametersValidator.cs, tests/Shark.Fido2.Common.Tests/Extensions/ConvertExtensionsTests.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/AttestationTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/HashProviderTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AssertionParametersValidatorTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationParametersValidatorTests.cs, tests/Shark.Fido2.Domain.Tests/AssertionCompleteResultTests.cs, tests/Shark.Fido2.Domain.Tests/AttestationCompleteResultTests.cs
- Extract validation logic to the separate classes
=> Extract validation logic to the separate classes

.github/workflows/scan_owasp.yml
=> Add OWASP scan

scripts/sqlserver/sqlserver_table_creation.sql
Update length of UserDisplayName column for SQL server
=> Update length of UserDisplayName column for SQL server

README.md
Update server side code samples in README file
=> Update server side code samples in README file

src/Shark.Fido2.Sample/Dockerfile
Delete production and test appsettings files from Docker file
=> Delete production and test appsettings files from Docker file

src/Shark.Fido2.Sample/Pages/Custom.cshtml, src/Shark.Fido2.Sample/wwwroot/js/site-custom.js
Remove username validation on Custom page of sample application to allow authentication with discoverable credentials
=> Remove username validation on Custom page of sample application

README.md
Add docker section to the README file and fix minor issues
=> Add docker section to the README file and fix minor issues

README.md
Update link to the Docker image
=> Update link to the Docker image

README.md
Update FIDO Conformance Tests results
=> Update FIDO Conformance Tests results

src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AndroidSafetyNetJwsResponseValidator.cs, src/Shark.Fido2.DynamoDB/CredentialRepository.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs
=> Add usage of time provider

src/Shark.Fido2.Domain/Credential.cs, src/Shark.Fido2.Domain/CredentialDescriptor.cs, src/Shark.Fido2.Domain/CredentialPublicKey.cs
Add XML comments to the domain models
=> Add XML comments to the domain models

src/Shark.Fido2.Core/Assertion.cs, tests/Shark.Fido2.Core.Tests/AssertionTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidSafetyNetAttestationStatementStrategyTests.cs
Fix grammar in assertion's error message
=> Fix grammar in assertion's error message

.github/workflows/deploy.yml
Update deployment script for sample app
=> Update deployment script for sample app

src/Shark.Fido2.Sample/appsettings.Production.json
Update production configuration for sample application
=> Update production configuration for sample application

src/Shark.Fido2.Core/Abstractions/IChallengeGenerator.cs, src/Shark.Fido2.Core/Abstractions/IUserIdGenerator.cs, src/Shark.Fido2.Core/Helpers/UserIdGenerator.cs
Improve logic of user id generator and add XML comments
=> Improve logic of user id generator and add XML comments

README.md
Update README with caching policy for FIDO metadata
=> Update README with caching policy for FIDO metadata

src/Shark.Fido2.Sample/Middlewares/DisableTrackMiddleware.cs, src/Shark.Fido2.Sample/Program.cs
Configure HSTS and disable optional HTTP methods for sample application
=> Configure HSTS and disable optional HTTP methods

src/Shark.Fido2.Sample/Pages/Shared/_Layout.cshtml
Update the footer for the sample application
=> Update the footer for the sample application

src/Shark.Fido2.Sample/Pages/Custom.cshtml, src/Shark.Fido2.Sample/Pages/Index.cshtml, src/Shark.Fido2.Sample/wwwroot/css/site.css
Add disclaimer for the sample application
=> Add disclaimer for the sample application

src/Shark.Fido2.Sample/Program.cs
Allow HTTP for Development environment for the sample application
=> Allow HTTP for Development environment for the sample application

src/Shark.Fido2.Sample/Program.cs
Disable HTTPS redirects for the sample application
=> Disable HTTPS redirects for the sample application

README.md
Update link to the application run under the docker
=> Update link to the application run under the docker

src/Shark.Fido2.Core/Shark.Fido2.Core.csproj, src/Shark.Fido2.DynamoDB/Shark.Fido2.DynamoDB.csproj, src/Shark.Fido2.InMemory/Shark.Fido2.InMemory.csproj, src/Shark.Fido2.Models/Shark.Fido2.Models.csproj, src/Shark.Fido2.SqlServer/Shark.Fido2.SqlServer.csproj
Extend information in NuGet packages
=> Extend information in NuGet packages

README.md
Update header's level in README
=> Update header's level in README

.github/workflows/build_docker_image.yml, .github/workflows/build_nuget_packages.yml
=> Release 1.1.2

tests/Shark.Fido2.Models.Tests/Mappers/PublicKeyCredentialAssertionMapperTests.cs, tests/Shark.Fido2.Models.Tests/Mappers/PublicKeyCredentialAttestationMapperTests.cs, tests/Shark.Fido2.Models.Tests/Mappers/PublicKeyCredentialRequestOptionsMapperTests.cs, tests/Shark.Fido2.Models.Tests/Responses/ServerResponseTests.cs
Extend unit tests for Models project
=> Extend unit tests for Models project

src/Shark.Fido2.Sample/Pages/Custom.cshtml, src/Shark.Fido2.Sample/Pages/Index.cshtml
Improve text of the labels for the sample application
=> Improve text of the labels for the sample application

src/Shark.Fido2.Sample/Pages/CredentialDetails.cshtml, src/Shark.Fido2.Sample/wwwroot/css/site.css, src/Shark.Fido2.Sample/wwwroot/js/assertion.js, src/Shark.Fido2.Sample/wwwroot/js/site-custom.js, src/Shark.Fido2.Sample/wwwroot/js/site.js
Improve sign-in flow in the sample application
=> Improve sign-in flow in the sample application

.github/workflows/build_nuget_packages.yml, Directory.Build.props
Add source link to the NuGet packages
=> Add source link to the NuGet packages

src/Shark.Fido2.Sample/Pages/Shared/_Layout.cshtml
Update title of the sample application
=> Update title of the sample application

src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor.Client/wwwroot/styles.css, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/wwwroot/js/assertion.js, src/Shark.Fido2.Sample/Controllers/LogoutController.cs, src/Shark.Fido2.Sample/Pages/CredentialDetails.cshtml, src/Shark.Fido2.Sample/Pages/Custom.cshtml, src/Shark.Fido2.Sample/Pages/DiscoverableCredentials.cshtml, src/Shark.Fido2.Sample/Pages/DiscoverableCredentials.cshtml.cs, src/Shark.Fido2.Sample/Pages/Shared/_Layout.cshtml, src/Shark.Fido2.Sample/wwwroot/css/site.css, src/Shark.Fido2.Sample/wwwroot/js/assertion.js, src/Shark.Fido2.Sample/wwwroot/js/attestation.js, src/Shark.Fido2.Sample/wwwroot/js/site-dc.js
Add support of discoverable credentials in sample application
=> Add support of discoverable credentials in sample application

src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor.Client/wwwroot/styles.css, src/Shark.Fido2.Sample/wwwroot/css/site.css
Improve styles of the button in the sample applications
=> Improve styles of the button in the sample applications

README.md, src/Shark.Fido2.Metadata.Core/Configurations/MetadataServiceConfiguration.cs, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/appsettings.Development.json, src/Shark.Fido2.Sample/appsettings.Development.json, src/Shark.Fido2.Sample/appsettings.Production.json, tests/Shark.Fido2.Core.Integration.Tests/appsettings.json
Update URL to the MDS root certificate
=> Update URL to the MDS root certificate

src/Shark.Fido2.Metadata.Core/Services/MetadataReaderService.cs
Properly dispose unmanaged cryptographic resources
=> Properly dispose unmanaged cryptographic resources

src/Shark.Fido2.Metadata.Core/Services/MetadataReaderService.cs
Refactor logic getting certificates from token in MDS
=> Refactor logic getting certificates from token in MDS

.github/workflows/build_docker_image.yml, .github/workflows/build_nuget_packages.yml, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor.csproj
=> Release 1.1.3

src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Controllers/AssertionController.cs, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Controllers/AttestationController.cs, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Program.cs, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/appsettings.Development.json, src/Shark.Fido2.Sample/Controllers/AssertionController.cs, src/Shark.Fido2.Sample/Controllers/AttestationController.cs, src/Shark.Fido2.Sample/Program.cs, src/Shark.Fido2.Sample/appsettings.Development.json, src/Shark.Fido2.Sample/appsettings.Production.json
=> Improve sessions management

README.md, src/Shark.Fido2.Metadata.Core/Configurations/MetadataServiceConfiguration.cs, src/Shark.Fido2.Sample/appsettings.Test.json, tests/Shark.Fido2.Core.Integration.Tests/appsettings.json
Increase default value for MaximumTokenSizeInBytes
=> Increase default value for MaximumTokenSizeInBytes

src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Program.cs, src/Shark.Fido2.Sample/Program.cs
Improve session management for sample applications
=> Improve session management for sample applications

src/Shark.Fido2.Core/Validators/AssertionResponseValidator.cs, src/Shark.Fido2.Core/Validators/AttestationObjectValidator.cs, tests/Shark.Fido2.Core.Tests/PublicKeyCredentialRequestOptionsBuilder.cs, tests/Shark.Fido2.Core.Tests/Validators/AssertionResponseValidatorTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationObjectValidatorTests.cs
- Fix user presence validation
- Add unit tests for attestation object validator
- Add unit tests for assertion response validator
=> Fix user presence validation

.github/workflows/build_docker_image.yml, .github/workflows/build_nuget_packages.yml, src/Shark.Fido2.Core/Shark.Fido2.Core.csproj, src/Shark.Fido2.Metadata.Core/Shark.Fido2.Metadata.Core.csproj, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor.csproj
=> Release 1.1.4

src/Shark.Fido2.DynamoDB/AmazonDynamoDbClientFactory.cs, src/Shark.Fido2.DynamoDB/DependencyInjection.cs, src/Shark.Fido2.DynamoDB/Shark.Fido2.DynamoDB.csproj, src/Shark.Fido2.InMemory/DependencyInjection.cs, src/Shark.Fido2.Sample/Program.cs, src/Shark.Fido2.Sample/appsettings.Development.json, src/Shark.Fido2.SqlServer/DependencyInjection.cs, src/Shark.Fido2.SqlServer/Shark.Fido2.SqlServer.csproj
=> Update storage providers

tests/Shark.Fido2.Common.Tests/Shark.Fido2.Common.Tests.csproj, tests/Shark.Fido2.Core.Integration.Tests/Shark.Fido2.Core.Integration.Tests.csproj, tests/Shark.Fido2.Core.Tests/Shark.Fido2.Core.Tests.csproj, tests/Shark.Fido2.Domain.Tests/Shark.Fido2.Domain.Tests.csproj, tests/Shark.Fido2.Metadata.Core.Tests/Shark.Fido2.Metadata.Core.Tests.csproj, tests/Shark.Fido2.Models.Tests/Shark.Fido2.Models.Tests.csproj
Update versions of the tests frameworks
=> Update versions of the tests frameworks

src/Shark.Fido2.Core/Helpers/ChallengeGenerator.cs, tests/Shark.Fido2.Core.Integration.Tests/CredentialsIntegrationTests.cs, tests/Shark.Fido2.Core.Tests/Helpers/ChallengeGeneratorTests.cs
Improve cryptographic challenges generator
=> Improve cryptographic challenges generator

src/Shark.Fido2.Core/Services/TpmsAttestationParserService.cs
=> Fix issue with TPM parser

src/Shark.Fido2.Core/Comparers/BytesArrayComparer.cs
Implement constant-time comparison of byte arrays in BytesArrayComparer
=> Implement constant-time comparison of byte arrays in BytesArrayComparer

src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Formatters/CustomConsoleFormatter.cs, src/Shark.Fido2.Sample/Formatters/CustomConsoleFormatter.cs
Improve custom console formatters
=> Improve custom console formatters

.github/workflows/build_docker_image.yml, .github/workflows/build_nuget_packages.yml, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor.Client/Shark.Fido2.Sample.Blazor.Client.csproj, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor.csproj, src/Shark.Fido2.Sample/Shark.Fido2.Sample.csproj, tests/Shark.Fido2.Core.Tests/Shark.Fido2.Core.Tests.csproj, tests/Shark.Fido2.Metadata.Core.Tests/Shark.Fido2.Metadata.Core.Tests.csproj
=> Release 1.1.7

.editorconfig, src/Shark.Fido2.Core/Assertion.cs, src/Shark.Fido2.Core/Validators/AttestationStatementValidators/AttestationCertificateValidator.cs, src/Shark.Fido2.DynamoDB/CredentialRepository.cs, src/Shark.Fido2.InMemory/CredentialRepository.cs, src/Shark.Fido2.Metadata.Core/Abstractions/IMetadataCachedService.cs, src/Shark.Fido2.Metadata.Core/Services/MetadataCachedNullService.cs, src/Shark.Fido2.Metadata.Core/Services/MetadataCachedService.cs, src/Shark.Fido2.Metadata.Core/Services/MetadataCachedTestService.cs, src/Shark.Fido2.SqlServer/CredentialRepository.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidKeyAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AndroidSafetyNetAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AppleAnonymousAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/AttestationCertificateValidatorTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/FidoU2fAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/PackedAttestationStatementStrategyTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationStatementValidators/TpmAttestationStatementStrategyTests.cs
=> Fix SonarQube issues

src/Shark.Fido2.Sample/Dockerfile
=> Fix warning in Dockerfile

tests/Shark.Fido2.Metadata.Core.Tests/Models/MetadataBlobPayloadEntryTests.cs
Extend unit tests for MetadataBlobPayloadEntry
=> Extend unit tests for MetadataBlobPayloadEntry

src/Shark.Fido2.Core/Handlers/ClientDataHandler.cs, tests/Shark.Fido2.Core.Tests/Handlers/ClientDataHandlerTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AssertionResponseValidatorTests.cs, tests/Shark.Fido2.Core.Tests/Validators/AttestationTrustworthinessValidatorTests.cs
=> Improve client data handler

src/Shark.Fido2.Core/Converters/CborConverter.cs
Add iteration limit to CborConverter for robustness
=> Add iteration limit to CborConverter for robustness

.github/workflows/build_docker_image.yml, .github/workflows/build_nuget_packages.yml, src/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor/Shark.Fido2.Sample.Blazor.csproj
=> Release 1.1.8

README.md, tests/Metadata/Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with configured vendor commands.json, tests/Metadata/Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with critical Basic Constraints in root certificate.json
Submit tests results from FIDO Conformance Tools v1.7.27.1
=> Submit tests results from FIDO Conformance Tools v1.7.27.1
